services:
  my-postgres:
    image: postgres:16
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: socialmedialite
    volumes:
      - socialmedialite_pgdata:/var/lib/postgresql/data

volumes:
  socialmedialite_pgdata:
